service: cloudless-app
frameworkVersion: "3"

custom: ${file(sls/custom.yml):custom}

provider:
  name: aws
  stage: ${opt:stage, 'staging'}
  stackName: ${self:custom.appName}-${opt:stage, 'staging'}
  region: ${opt:region, ${env:AWS_REGION, 'eu-central-1'}}
  profile: ${env:AWS_PROFILE, 'ql4b'}
  iam: ${file(./sls/iam.yml):iam}

  httpApi:
    cors: true
  
  # uncomment if necessary
  # environment: ${file(sls/env.yml):environment}
  
functions: ${file(sls/functions.yml):functions}

# uncomment if necessary
# layers: ${file(sls/layers.yml):layers}
